### PR TITLE
Add method AddClusterWithID

### PR DESCRIPTION
**Pull request by ernestas-poskus**
@quux00 

Adding method which lets to specify cluster position

### CODE REVIEW

**Comment by ernestas-poskus** [comment]
@dennwc but this will break stable API gopkg.in/istreamdata/orientgo.v2

**Comment by dennwc** [comment]
@ernestas-poskus No. Only for `DBSession` type and `obinary` package. Both are considered internal. I should document that fact, by the way.
High-level API (in `client.go`) will just receive additional method `AddClusterWithID`, so it's okay from users perspective, I think.

**Comment by ernestas-poskus** [comment]
updated

**Comment by dennwc** [comment]
You forgot to add the last function:

``` Go
func (db *Database) AddCluster(name string) (int16, error) {
  return db.AddClusterWithID(name, -1)
}
```

Or it will really break stable API for `Database`.

**Comment by dennwc** [comment]
The `AddCluster` method that I was talking about should belong to client.go, not obinary package.
You see, DBSession is a interface for DB connection with minimal set of methods. It allows to implement different wire protocols. Any convenient methods such as `AddCluster` should go to high-level API in client.go.

**Comment by dennwc** [comment]
Right. The last change: drop `AddCluster` from `DBSession`, and I'll merge it.

**Comment by dennwc** [comment]
Looks good. Merged. Thank you again!

**Comment by ernestas-poskus** [comment]
Thanks for comments

**Pull request merged**
