### PR TITLE
Add database Dial example

### PR DESCRIPTION
**Pull request by ernestas-poskus**
https://github.com/istreamdata/orientgo/issues/31

@dennwc @theduke

Adding Dial example

### CODE REVIEW

**Comment by dennwc** [comment]
1) Import path should be `gopkg.in/istreamdata/orientgo.v2/obinary`.

2) I think we can make a Dial example much shorter for README - only the necessary lines. Everything else will be visible via godoc.

3) Examples [can be built into](https://blog.golang.org/examples) test files. They will be tested for compilation automatically and will appear in godoc in a natural way. So please change everything accordingly to "Large examples" section of documentation.

**Comment by ernestas-poskus** [comment]
> I think we can make a Dial example much shorter for README - only the necessary lines. Everything else will be visible via godoc.

made it a little shorter

> 3) Examples can be built into test files. They will be tested for compilation automatically and will appear in godoc in a natural way. So please change everything accordingly to "Large examples" section of documentation.

then example will be non-copy-able, I mean user will have to figure out import paths.

How about I will add just a link to examples folder ?

**Comment by dennwc** [comment]
I still think it's too large for README. Example code is good itself, but not for the project main page. Would you mind leaving something like Dial-Open-SQLQuery for README without any details at all? You can even drop error handling there.

> then example will be non-copy-able, I mean user will have to figure out import paths.

You can use full import paths in example by naming it `package orient_test`. Please check [this example](https://golang.org/pkg/os/signal/#example_Notify). It's a copy-able code with full godoc support. You can't underestimate how useful such examples could be - anyone can see it right after function documentation :)

Also, please remove HandleError wrapper. Panics are ok for examples.

**Comment by ernestas-poskus** [comment]
Updated README with file reference, added example to root of the package.

**Comment by dennwc** [comment]
Looks great! Thank you for you work  :)

**Pull request merged**
